# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=150)),
                ('tweet_location', models.CharField(max_length=20)),
            ],
        ),
    ]
